# Copyright (c) 2020 Allan Mobley. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:

# Specify a particular version of the .NET SDK
- task: UseDotNet@2
  displayName: 'Set SDK'
  inputs:
    packageType: sdk
    version: 3.1.201
    installationPath: $(Agent.ToolsDirectory)/UseDotNet

# Build site
- script: dotnet build --configuration Release
  workingDirectory: src
  displayName: Build Mobsites